apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: job-check-filesystem
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        name: check-filesystem
        command:
        - /bin/bash
        - -c
        - |
          while [ 1 ]; do
            oc get -n ibm-spectrum-scale filesystem localfilesystem -o json | jq -e '.status.conditions[] | select(.type == "Success" and .status == "True" and .reason == "Created")'
            if [ "$?" == "0" ]; then
              exit 0
            else
              echo "Not ready, checking again in 5 seconds"
              sleep 5
            fi
          done
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 3600
