---
apiVersion: fusion.storage.openshift.io/v1alpha1
kind: FusionAccess
metadata:
  name: fusionaccess-object
  annotations:
    argocd.argoproj.io/sync-wave: "-25" 
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=True
spec:
  storageScaleVersion: {{ .Values.storageScaleVersion | quote }}
  storageDeviceDiscovery:
    create: true
