apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: job-make-localdisk
spec:
  template:
    spec:
      containers:
      - image: {{ .Values.job.image }}
        name: make-localdisk
        command:
        - /bin/bash
        - -c
        - |
          FS_NODE=$(oc get nodes -l node-role.kubernetes.io/worker -o json  | jq 'first(.items)[0].metadata.name')
          oc apply -f=- << EOF
          apiVersion: scale.spectrum.ibm.com/v1beta1
          kind: LocalDisk
          metadata:
            name: shareddisk1
            namespace: ibm-spectrum-scale
          spec:
            # After successful creation of the local disk, this parameter is no longer used
            device: /dev/nvme1n1
            node: $FS_NODE
            nodeConnectionSelector:
              matchExpressions:
              - key: node-role.kubernetes.io/worker
                operator: Exists
                name: label-storage-nodes
          EOF

          while [ 1 ];
          do
            oc get LocalDisk shareddisk1 -n ibm-spectrum-scale -o json | jq -e '.status.conditions[] | select(.type == "Ready" and .status == "True")'
            if [ "$?" == 0 ]; then
              echo "Disk is ready, exiting"
              exit 0
            else
              echo "Disk is not yet ready, waiting..."
              sleep 5
            fi
          done

      dnsPolicy: ClusterFirst
      restartPolicy: Never
      serviceAccountName: {{ .Values.serviceAccountName }}
      terminationGracePeriodSeconds: 400
