---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: fusion-pullsecret
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: fusion-pullsecret
  dataFrom:
  - extract:
      key: {{ .Values.fusionPullsecret.key }}
