---
apiVersion: scale.spectrum.ibm.com/v1beta1
kind: Cluster
metadata:
  name: ibm-spectrum-scale
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  pmcollector:
    nodeSelector:
      scale.spectrum.ibm.com/daemon-selector: ""
  daemon:
    nsdDevicesConfig:
      localDevicePaths:
      - devicePath: /dev/disk/by-id/*
        deviceType: generic
    clusterProfile:
      controlSetxattrImmutableSELinux: "yes"
      enforceFilesetQuotaOnRoot: "yes"
      ignorePrefetchLUNCount: "yes"
      initPrefetchBuffers: "128"
      maxblocksize: 16M
      prefetchPct: "25"
      prefetchTimeout: "30"
    nodeSelector:
      scale.spectrum.ibm.com/daemon-selector: ""
    roles:
    - name: client
      resources:
        cpu: "2"
        memory: 4Gi
    - name: storage
      resources:
        cpu: "2"
        memory: 8Gi
  license:
    accept: true
    license: data-management
  networkPolicy: {}

