apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ibm-spectrum-scale-virt
  annotations:
    storageclass.kubevirt.io/is-default-virt-class: "true"
parameters:
  volBackendFs: localfilesystem
provisioner: spectrumscale.csi.ibm.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: true
