---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

fusionPullsecret:
  key: secret/data/hub/fusion-pullsecret

serviceAccountName: storage-node-label-sa

storageScaleVersion: 'v5.2.3.1.dev3'

rbac:
  roles:
    - name: label-storage-nodes
      createRole: true
      apiGroups:
        - '""'
      scope:
        cluster: true
      resources:
        - nodes
        - LocalDisk
      verbs:
        - "get"
        - "list"
        - "patch"
        - "update"
        - "create"
  roleBindings:
    - name: label-storage-nodes
      createBinding: true
      scope:
        cluster: true
        namespace: ""
      subjects:
        kind: ServiceAccount
        name: storage-node-label-sa
        namespace: ibm-fusion-access
        apiGroup: ""
      roleRef:
        kind: ClusterRole
        name: label-storage-nodes

job:
  image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest

fusionStorage:
  namespace: ibm-fusion-access
