---
- name: Patch OpenShift pull secret
  hosts: localhost
  connection: local
  gather_facts: false
  become: false
  vars:
    auth_realm: quay.io/openshift-storage-scale
    auth_email: ""
    auth_secret: ""
  tasks:
    - name: Retrieve secret to patch
      kubernetes.core.k8s_info:
        kind: Secret
        namespace: openshift-config
        name: pull-secret
      register: openshift_ps

    - name: Set data structure for auth to update
      ansible.builtin.set_fact:
        custom_auth:
          auth: '{{ auth_secret }}'
          email: '{{ auth_email }}'

    - name: Extract dockerconfigjson and decode it
      ansible.builtin.set_fact:
        dockercfgjson: "{{ openshift_ps.resources[0].data['.dockerconfigjson'] | b64decode }}"

    - name: Extract auths
      ansible.builtin.set_fact:
        auths: "{{ dockercfgjson.auths }}"

    - name: Build new auth structure
      ansible.builtin.set_fact:
        dockercfgjson: "{{ auths | combine({ auth_realm: { 'auth':  auth_secret, 'email': auth_email }}) }}"

    - name: Re-encode secret
      ansible.builtin.set_fact:
        secret_data: "{{ { 'data': { '.dockerconfigjson': dockercfgjson | to_json | b64encode } } }}"

    - name: Update original object
      ansible.builtin.set_fact:
        new_object: "{{ openshift_ps.resources[0] | combine(secret_data) }}"

    - name: Update secret object
      kubernetes.core.k8s:
        definition: "{{ new_object | to_json }}"
        state: patched
